name: Cache all sessions (codeocean)

on: 
  push:
    tags:        
      - '**'           
  workflow_dispatch:
          
jobs:
  package:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]
    permissions: write-all

    steps:

    - name: Configure aws credentials
      env:
        AWS_IAM_ROLE: ${{ vars.AWS_IAM_ROLE }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ vars.AWS_IAM_ROLE }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
    - name: Launch
      env:
        DBHUB_API_KEY: ${{ secrets.DBHUB_API_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        CODE_OCEAN_API_TOKEN: ${{ secrets.CODE_OCEAN_API_TOKEN }}
        CODE_OCEAN_DOMAIN: ${{ secrets.CODE_OCEAN_DOMAIN }}
      run: |
        pip install npc_lims
        run_session_cache_capsule
